version: '3'
services:
  keep2todoist:
    container_name: keep2todoist
    build: app
    restart: always
    volumes:
      - type: bind
        source: ./app/config.yaml
        target: /app/config.yaml