update_interval_s: 60
google_username: yourUsername
google_password: canBeAnAppPassword
todoist_api_token: todoistApiKey
keep_lists:  # list your keep lists on this level
  - Todo:
    due_str_en: today # optional: you can set a due date in english here
    # if todoist_project is not set your task will go into the todoist inbox
  - Shopping:
    todoist_project: 'Shopping' # optional: you can choose a project for todoist here
  - Test: #entry without optional attribtues - notice the colon!